### ISSUE TITLE
Hello, it seems to work in python2 only

### ISSUE THREAD

**Issue by jaromrax** [vctandrade/flask-digest#1]
Is that correct? Any plan to move to python3?
Thanks 
Jarom

**Comment by vctandrade** [comment]
Sorry for such a late response. I'm not maintaining this project anymore, so no plans to port it to python3. However it seems that someone already did this https://github.com/db48x/flask-digest.

**Comment by vctandrade** [comment]
Took a while, but I ended up upgrading to Python 3.
